In [14]:
import pandas as pd
import openpyxl

In [15]:
df = pd.read_excel(r"C:\Users\Griffin Bohannon\Desktop\Coding\Python\Projects\Customer_Analysis\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [16]:
df = df.drop_duplicates()

In [17]:
df.drop(columns = "Not_Useful_Column")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [18]:
#Used the strip function to get rip of random values and symbols (mainly to get practice with the strip funciton)
df["Last_Name"] = df["Last_Name"].str.lstrip("...")
df["Last_Name"] = df["Last_Name"].str.lstrip("/")
df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df

#Could use the strip function like this 
#   df["Last_Name"] = df["Last_Name"].str.strip("123._/")

C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4094028801.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last_Name"] = df["Last_Name"].str.lstrip("...")
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4094028801.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last_Name"] = df["Last_Name"].str.lstrip("/")
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4094028801.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last_Name"] = df["Last_Name"].str.rstrip("_")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [19]:
#Cleaning data of everything other than letters and numbers ('^' means everything except) to make everything similar
df["Phone_Number"] = df["Phone_Number"].str.replace('[^0-9]','',regex=True)

#Using lambda to clean and format the data to the proper phone number format

df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))

df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])

#Removing all other random null values, etc.
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
df["Phone_Number"] = df["Phone_Number"].str.replace('--','')
df

C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4278640275.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].str.replace('[^0-9]','',regex=True)
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4278640275.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4278640275.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4278640275.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\4278640275.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"] = df["Phone_Number"].str.replace('--','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [32]:
#Spliting the Address Column on the commas to get Address, State, and ZipCode
df[["Address", "State", "Zip_Code"]] = df["Address"].str.split(',', expand=True)
df

ValueError: Columns must be same length as key

In [37]:
#Using the Replace Function to get some uniformity with the code 
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes', 'Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No', 'N')

df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes', 'Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No', 'N')
df

C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\1014215735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Paying Customer"] = df["Paying Customer"].str.replace('Yes', 'Y')
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\1014215735.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Paying Customer"] = df["Paying Customer"].str.replace('No', 'N')
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\1014215735.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes', 'Y')
C:\Users\Griffin Bohannon\AppData\Local\Temp\ipykernel_20196\1014215735.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No', 'N')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,"(Address, State, Zip_Code)",State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,True,"[123 Shire Lane, Shire]",Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False,[93 West Main Street],None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True,[298 Drugs Driveway],None,None
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,True,"[980 Paper Avenue, Pennsylvania, 18503]",Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,[123 Dragons Road],None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True,[768 City Parkway],None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,False,[1209 South Street],None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,[98 Clue Drive],None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,False,[123 Middle Earth],None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,True,"[25th Main Street, New York]",New York,None
10,1011,Samwise,Gamgee,,612 Shire Lane,Y,N,True,"[612 Shire Lane, Shire]",Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True,[2394 Hogwarts Avenue],None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,[2039 Main Street],None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,[343 City Parkway],None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,[214 HR Avenue],None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,[2395 Hogwarts Avenue],None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,False,"[121 Paper Avenue, Pennsylvania]",Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True,[3498 Super Lane],None,None
18,1019,Creed,Braton,,N/a,N/a,Y,True,[N/a],None,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,True,"[910 Tatooine Road, Tatooine]",Tatooine,None

In [41]:
#Getting ride of 'N/A's and Null Values(NaN)
df = df.replace('N/A','')
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,"(Address, State, Zip_Code)",State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,True,"[123 Shire Lane, Shire]",Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False,[93 West Main Street],,
2,1003,Walter,White,,298 Drugs Driveway,N,,True,[298 Drugs Driveway],,
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,True,"[980 Paper Avenue, Pennsylvania, 18503]",Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,[123 Dragons Road],,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True,[768 City Parkway],,
6,1007,Jeff,Winger,,1209 South Street,N,N,False,[1209 South Street],,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,[98 Clue Drive],,
8,1009,Gandalf,,,123 Middle Earth,Y,,False,[123 Middle Earth],,
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,True,"[25th Main Street, New York]",New York,
10,1011,Samwise,Gamgee,,612 Shire Lane,Y,N,True,"[612 Shire Lane, Shire]",Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,[2394 Hogwarts Avenue],,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,[2039 Main Street],,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,[343 City Parkway],,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,[214 HR Avenue],,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,[2395 Hogwarts Avenue],,
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,False,"[121 Paper Avenue, Pennsylvania]",Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,[3498 Super Lane],,
18,1019,Creed,Braton,,N/a,N/a,Y,True,[N/a],,
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,True,"[910 Tatooine Road, Tatooine]",Tatooine,

In [43]:
#Removing Records of Customers who do not want to be contacted

for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,"(Address, State, Zip_Code)",State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,True,"[123 Shire Lane, Shire]",Shire,
2,1003,Walter,White,,298 Drugs Driveway,N,,True,[298 Drugs Driveway],,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,[123 Dragons Road],,
6,1007,Jeff,Winger,,1209 South Street,N,N,False,[1209 South Street],,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,[98 Clue Drive],,
8,1009,Gandalf,,,123 Middle Earth,Y,,False,[123 Middle Earth],,
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,True,"[25th Main Street, New York]",New York,
10,1011,Samwise,Gamgee,,612 Shire Lane,Y,N,True,"[612 Shire Lane, Shire]",Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,[2394 Hogwarts Avenue],,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,[2039 Main Street],,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,[343 City Parkway],,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,[214 HR Avenue],,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,[2395 Hogwarts Avenue],,
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,False,"[121 Paper Avenue, Pennsylvania]",Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,[3498 Super Lane],,
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,True,"[910 Tatooine Road, Tatooine]",Tatooine,

In [45]:
#Removing Records of Customers that do not have a phone number inputed
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,"(Address, State, Zip_Code)",State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,True,"[123 Shire Lane, Shire]",Shire,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,[123 Dragons Road],,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,[98 Clue Drive],,
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,True,"[25th Main Street, New York]",New York,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,[2039 Main Street],,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,[343 City Parkway],,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,[214 HR Avenue],,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,[2395 Hogwarts Avenue],,
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,False,"[121 Paper Avenue, Pennsylvania]",Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,True,"[910 Tatooine Road, Tatooine]",Tatooine,

In [47]:
#Reseting the Index for better readability 
df = df.reset_index(drop=True)